### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by JamalMulla** [ed741/cain#23]
I'm using the instructions in the README to build and run. All examples give the following stacktrace
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at uk.co.edstow.cain.Main.main(Main.java:9)`
Caused by: org.reflections.ReflectionsException: Scanner MethodAnnotationsScanner was not configured
        at org.reflections.Store.get(Store.java:39)
        at org.reflections.Store.get(Store.java:61)
        at org.reflections.Store.get(Store.java:46)
        at org.reflections.Reflections.getConstructorsAnnotatedWith(Reflections.java:515)
        at uk.co.edstow.cain.FileRun.<clinit>(FileRun.java:42)
         ... 1 more
```

Tests pass successfully.

**Comment by ed741** [comment]
I hope that the latest push the master fixes this issue, but it also significantly changes the json format in other ways. hopefully for the better in the longer run. But the README should now be more up to date and helpful.
